### ISSUE TITLE
 ERROR: Failed building wheel for fir1

### ISSUE THREAD

**Issue by manojasati** [berndporr/fir1#2]
I am getting the following error while installing the module in anaconda..

 ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\.....\\AppData\\Local\\Temp\\pip-install-a1twbd7_\\fir1\\setup.py'"'"'; __file__='"'"'C:\\Users\\<user>\\AppData\\Local\\Temp\\pip-install-a1twbd7_\\fir1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\....\AppData\Local\Temp\pip-record-v_kjzvwi\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\....\AppData\Local\Temp\pip-install-a1twbd7_\fir1\
    Complete output (11 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    copying fir1.py -> build\lib.win-amd64-3.7
    running build_ext
    building '_fir1' extension
    swigging fir1.i to fir1_wrap.cpp
    swig.exe -python -c++ -py3 -o fir1_wrap.cpp fir1.i
    error: command 'swig.exe' failed: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\....\\AppData\\Local\\Temp\\pip-install-a1twbd7_\\fir1\\setup.py'"'"'; __file__='"'"'C:\\Users\\....\\AppData\\Local\\Temp\\pip-install-a1twbd7_\\fir1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\....\AppData\Local\Temp\pip-record-v_kjzvwi\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by berndporr** [comment]
You need to install swig. See the log above which reports that swig is not installed.However, I'd recommend to just install the compiled package with 'pip' via the anaconda console.www.berndporr.me.ukOn 31 Jul 2019 10:59 am, Manoj Kumar Asati <notifications@github.com> wrote:I am getting the following error while installing the module in anaconda..
ERROR: Command errored out with exit status 1:
command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Manoj\AppData\Local\Temp\pip-install-a1twbd7_\fir1\setup.py'"'"'; file='"'"'C:\Users\Manoj\AppData\Local\Temp\pip-install-a1twbd7_\fir1\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\Manoj\AppData\Local\Temp\pip-record-v_kjzvwi\install-record.txt' --single-version-externally-managed --compile
cwd: C:\Users\Manoj\AppData\Local\Temp\pip-install-a1twbd7_\fir1
Complete output (11 lines):
running install
running build
running build_py
creating build
creating build\lib.win-amd64-3.7
copying fir1.py -> build\lib.win-amd64-3.7
running build_ext
building 'fir1' extension
swigging fir1.i to fir1_wrap.cpp
swig.exe -python -c++ -py3 -o fir1_wrap.cpp fir1.i
error: command 'swig.exe' failed: No such file or directory
----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Manoj\AppData\Local\Temp\pip-install-a1twbd7\fir1\setup.py'"'"'; file='"'"'C:\Users\Manoj\AppData\Local\Temp\pip-install-a1twbd7_\fir1\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record 'C:\Users\Manoj\AppData\Local\Temp\pip-record-v_kjzvwi\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
